AllCops:
  NewCops: enable
  Exclude:
    - 'db/**/*'
    - 'tmp'
    - 'config/puma.rb'
    - 'config/initializers/devise.rb'
    - 'bin/*'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'
Style/FrozenStringLiteralComment:
  EnforcedStyle: never
Bundler/OrderedGems:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/SymbolArray:
  Enabled: false
Layout/ArgumentAlignment:
  Enabled: false
Layout/LineLength:
  Max: 120


