default: &default
  adapter: postgresql
  encoding: unicode
  host: postgres
  username: heroku_username
  password: heroku_password
  pool: 5

development:
  <<: *default
  database: app_development

staging:
  <<: *default
  database: app_staging

test:
  <<: *default
  database: app_test
